---
- name: make .R
  file: path="{{home}}/.R" state=directory
  sudo: no
  when: ansible_os_family == 'Darwin'

- name: use gcc installed by brew in compiling R libraries
  copy: dest="{{home}}/.R/MakeVars" content="CC=gcc-5\nCXX=g++-5"
  sudo: no
  when: ansible_os_family == 'Darwin'

# install R packages; the code was taken from here http://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
- name: install R packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('{{r_pkg__repo}}')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items: r_pkg__packages

- name: get R package sources
  get_url: url="{{ item.url }}" dest="{{lookup('env','TMPDIR') | default('/tmp') }}{{item.url | basename}}"
  with_items: r_pkg__src_packages
  register: r_src_downloaded

- name: install R packages from source
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item.item.name }}' %in% installed.packages()[,'Package']) || '{{item.item.version}}' != installed.packages()['{{item.item.name}}', 'Version']) { install.packages(pkgs='{{ item.dest }}', type='source', repo=NULL{% if item.item.conf_args is defined %}, configure.args='{{item.item.conf_args}}'{% endif %}); print('Added');} else { print('Already installed'); }"
  register: r_src_result
  failed_when: "r_src_result.rc != 0 or 'had non-zero exit status' in r_src_result.stderr"
  changed_when: "'Added' in r_src_result.stdout"
  with_items: r_src_downloaded.results
