---

# install R packages; the code was taken from here http://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
- name: install R packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('{{r_pkg__repo}}')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items: r_pkg__packages
