---

- name: install supervisord
  pip: name=supervisor state=present

- name: make directories
  sudo: yes
  file: path={{item}} state=directory mode=0755
  with_items:
    - "{{supervisord__conf_dir}}"
    - "{{supervisord__log_dir}}"
    - "{{supervisord__pid_dir}}"
  ignore_errors: yes # to avoid an error on Mac OSX (/tmp is a link)

- name: setup supervisord-managed applications
  template: src=conf.d/{{item}} dest={{supervisord__conf_dir}}/{{item}}
  with_items:
    - google-ime-skk.conf

- name: put supervisord conf
  template: src=etc/supervisord.conf.j2 dest=/usr/local/share/supervisord.conf
  notify: restart supervisord

- include: start_in_mach.yml
  when: ansible_os_family == 'Darwin'
