---

- name: install supervisord
  pip: name=supervisor state=present extra_args='--user' executable=pip2

- name: make directories
  file: path={{item}} state=directory mode=0755
  with_items:
    - "{{supervisord__conf_dir}}"
    - "{{supervisord__log_dir}}"
    - "{{supervisord__pid_dir}}"

- name: setup supervisord-managed applications
  template: src=conf.d/{{item}} dest={{supervisord__conf_dir}}/{{item}}
  with_items:
    - google-ime-skk.conf

- name: put supervisord conf
  template: src=etc/supervisord.conf.j2 dest="{{supervisord__conf_dir}}/supervisord.conf"
  notify: restart supervisord

- include: start_in_mach.yml
  when: ansible_os_family == 'Darwin'
