---
sys_pkg__common:
    - ffmpeg
    - ctags
    - sbt
    - ghc
    - bash-completion
    - git
    - tig
    - r
    - tmux
    - go
    - maven
    - protobuf
    - antlr
    - binutils
    - emacs
    - jq
    - ripgrep
    - w3m
    - ngrep
    - unp
    - socat
    - source-highlight
    - htop

sys_pkg__arch:
    - aspell
    - aspell-en
    - bash ## /bin/bash is too old; don't forget to add /usr/local/bin/bash to /etc/shells and run 'chsh -s /usr/local/bin/bash'
    - gcc-fortran
    - helm
    - ibus
    - ibus-skk
    - inetutils
    - kubectl
    - kubeseal
    - lesspipe
    - make
    - mupdf
    - nodejs
    - npm
    - ruby # since there is no system ruby
    - openssh
    - python-pipenv
    - python-pygments
    - terraform

sys_pkg__arch_with_yaourt:
    - fzf
    - gauche
    - jdk
    - mono
    - rustup
    - sshrc
    - rbenv
    - pv
    - texlive
    - texlive-langjapanese
    - ttf-fira-code

sys_pkg__mach:
    - atool
    - node
    - vim
    - coreutils
    - cmake
    - dasht
    - elinks
    - findutils
    - flock
    - fzf
    - global
    - ricty
    - ruby-build
    - rbenv
    - cmigemo
    - python
    - poppler
    - gnu-time
    - gcc
    - gradle
    - hub
    - lesspipe
    ## to install igraph in R
    - libxml2
    - llvm
    - pv
    - rustup
    - sshrc
    - q
    - yarn

sys_pkg__brew_options:
    vim: with-client-server,with-lua,with-luajit
    llvm: with-clang
    global: with-ctags,with-pygments,with-sqlite3
    dasht: ignore-dependencies
sys_pkg__brew_state:
    libxml2: linked
sys_pkg__mach_with_cask:
     # fails when installed. TODO: avoid the error
     # - intellij-idea-ce
     #not working for now. TODO: find out a way to install automatically
     #    - aquaskk
    - virtualbox
    - vagrant
    - dia
    - font-fira-code
    # avoid conflict by not installing anaconda
    #- anaconda
    - visual-studio-code
    - tabula

sys_pkg__brew_tap:
    - sanemat/font # ricty
    - homebrew/versions
    - homebrew/science
    - aereal/aereal_casks # aquaskk
    - discoteq/discoteq # flock
    - caskroom/fonts # fira code
    - ttf-fira-code
