---
sys_pkg__common:
    - ctags
    - scala
    - sbt
    - ghc
    - bash-completion
    - gcc
    - git
    - tig
    - r
    - tmux
    - q
    - go
    - vim
    - gradle
    - maven
    - rust
    - protobuf
    - antlr

sys_pkg__arch:
    - ibus
    - ibus-skk
    - intellij-idea-community-edition
      # TODO enable AUR and use yaourt to install the following
    - yaourt
    - cmigemo-git
    - haskell-hunit
    - python2-pip

sys_pkg__mach:
    - coreutils
    - brew-cask
    - ricty
    - ruby-build
    - rbenv
    - cmigemo
    - autoenv
    - python
    - gnu-time

sys_pkg__brew_options:
    vim: with-client-server,with-lua,with-luajit
sys_pkg__mach_with_cask:
    - intellij-idea-ce
     #not working for now
     #    - aquaskk
    - virtualbox
    - vagrant

sys_pkg__brew_tap:
    - sanemat/font # ricty
    - homebrew/versions
    - phinze/cask # homebrew cask
    - aereal/aereal_casks # aquaskk
