---
sys_pkg__common:
    - ctags
    - scala
    - sbt
    - ghc
    - bash-completion
    - git
    - tig
    - r
    - tmux
    - go
    - maven
    - protobuf
    - antlr
    - binutils
    - gauche
    - emacs

sys_pkg__arch:
    - chromium
    - ibus
    - ibus-skk
    - intellij-idea-community-edition
    - make
      # TODO enable AUR and use yaourt to install the following
    - yaourt
    - cmigemo-git
    - haskell-hunit
    - python2-pip
    - python2-virtualenv
    - gvim
    - gcc-fortran
    - nodejs
    - npm
    - ruby # since there is no system ruby
    - yakuake
    ## required after installation of OS
    - plasma
    - synaptics
    - nvidia
    - nvidia-utils
    - lib32-nvidia-libgl
    - lib32-nvidia-utils
    - bumblebee
    - xf86-video-intel
    - mesa
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    - xorg-twm
    - xorg-xclock
    - xterm
    - netctl
    - wpa_supplicant
    - dialog
    - openssh

sys_pkg__arch_with_yaourt:
    - chromium-widevine
    - gcc-multilib
    - gradle
    - rust
    - sshrc
    - cargo
    - q

sys_pkg__mach:
    - node
    - vim
    - coreutils
    - cmake
    - ricty
    - ruby-build
    - rbenv
    - cmigemo
    - autoenv
    - python
    - gnu-time
    - gcc
    - gradle
    - llvm
    - rust
    - sshrc
    - q

sys_pkg__brew_options:
    vim: with-client-server,with-lua,with-luajit
    llvm: with-clang
sys_pkg__mach_with_cask:
     # fails when installed. TODO: avoid the error
     # - intellij-idea-ce
     #not working for now. TODO: find out a way to install automatically
     #    - aquaskk
    - virtualbox
    - vagrant
    - dia
    # avoid conflict by not installing anaconda
    #- anaconda
    - visual-studio-code

sys_pkg__brew_tap:
    - sanemat/font # ricty
    - homebrew/versions
    - aereal/aereal_casks # aquaskk
