---
sys_pkg__common:
    - ctags
    - scala
    - sbt
    - ghc
    - bash-completion
    - git
    - tig
    - r
    - tmux
    - go
    - maven
    - protobuf
    - antlr
    - binutils
    - gauche
    - emacs
    - jq
    - ripgrep
    - the_silver_searcher

sys_pkg__arch:
    - aspell
    - aspell-en
    - avr-binutils
    - avr-gcc
    - avr-libc
    - chromium
    - docker
    - dropbox
    - ibus
    - ibus-skk
    - intellij-idea-community-edition
    - make
      # TODO enable AUR and use yaourt to install the following
    - yaourt
    - haskell-hunit
    - python2-pip
    - python2-virtualenv
    - python-pygments
    - gvim
    - gcc-fortran
    - mupdf
    - nodejs
    - npm
    - ruby # since there is no system ruby
    - skk-jisyo
    - texlive-most
    - texlive-langjapanese
    - yakuake
    ## required after installation of OS
    - plasma
    - synaptics
    - nvidia
    - nvidia-utils
    - bumblebee
    - xf86-video-intel
    - mesa
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    - xorg-twm
    - xorg-xclock
    - xterm
    - ttf-symbola
    - netctl
    - wpa_supplicant
    - dialog
    - openssh

sys_pkg__arch_with_yaourt:
    - 1pass-hg
    - arm-none-eabi-gcc
    - arm-none-eabi-newlib
    - chromium-widevine
    - cmigemo-git
    - coursera-dl
    - dfu-programmer
    - dfu-util
    - emojione-color-font
    - flashplugin
    - gcc-multilib
    - global
    - gradle
    - jdk
    - rust
    - sshrc
    - cargo
    - rbenv
    - pepper-flash
    - q
    - ttf-ricty
    - virtualbox
    - virtualbox-host-modules-arch
    - yarn

sys_pkg__mach:
    - node
    - vim
    - coreutils
    - cmake
    - global
    - ricty
    - ruby-build
    - rbenv
    - cmigemo
    - autoenv
    - python
    - gnu-time
    - gcc
    - gradle
    ## to install igraph in R
    - libxml2
    - llvm
    - rust
    - sshrc
    - q
    - yarn

sys_pkg__brew_options:
    vim: with-client-server,with-lua,with-luajit
    llvm: with-clang
    global: with-ctags,with-pygments
sys_pkg__brew_state:
    libxml2: linked
sys_pkg__mach_with_cask:
     # fails when installed. TODO: avoid the error
     # - intellij-idea-ce
     #not working for now. TODO: find out a way to install automatically
     #    - aquaskk
    - virtualbox
    - vagrant
    - dia
    # avoid conflict by not installing anaconda
    #- anaconda
    - visual-studio-code
    - pdftotext
    - tabula

sys_pkg__brew_tap:
    - sanemat/font # ricty
    - homebrew/versions
    - homebrew/science
    - aereal/aereal_casks # aquaskk
