---
sys_pkg__common:
    - ctags
    - scala
    - sbt
    - ghc
    - bash-completion
    - gcc
    - git
    - tig
    - r
    - tmux
    - q
    - go
    - gradle
    - maven
    - rust
    - protobuf
    - antlr
    - binutils
    - gauche

sys_pkg__arch:
    - ibus
    - ibus-skk
    - intellij-idea-community-edition
      # TODO enable AUR and use yaourt to install the following
    - yaourt
    - cmigemo-git
    - haskell-hunit
    - python2-pip
    - gvim
    - nodejs
    - npm

sys_pkg__mach:
    - node
    - vim
    - coreutils
    - ricty
    - ruby-build
    - rbenv
    - cmigemo
    - autoenv
    - python
    - gnu-time
    - Caskroom/cask/anaconda

sys_pkg__brew_options:
    vim: with-client-server,with-lua,with-luajit
sys_pkg__mach_with_cask:
     # fails when installed. TODO: avoid the error
     # - intellij-idea-ce
     #not working for now. TODO: find out a way to install automatically
     #    - aquaskk
    - virtualbox
    - vagrant
    - dia

sys_pkg__brew_tap:
    - sanemat/font # ricty
    - homebrew/versions
    - aereal/aereal_casks # aquaskk
