---

- name: make directories for gitignore
  file: path={{home}}/.config/git state=directory

- name: make symlinks to config files
  file: src={{home}}/dotfiles/{{item.src}} dest={{home}}/{{item.dest | default("." + item.src)}} state=link
  with_items: link_cfg__dotfiles
