---

- name: make directories
  file: path="{{item.dir}}" state=directory
  with_items: local_pkg__directories

- name: perform required git clones
  git:  dest="{{item.dest}}" repo="{{item.repo}}" remote="{{item.remote | default('origin') }}"
  with_items: local_pkg__git_clone

- name: install packages using pip
  pip: name={{item}} state=present executable=pip2 extra_args='--user'
  with_items: local_pkg__pip

- name: install google-ime-skk using a system ruby
  gem: name=google-ime-skk state=present executable=/usr/bin/gem

- name: get google-ime-skk gem path
  command: gem which google-ime-skk
  changed_when: False
  register: google_ime_skk_path

- name: make a symlink to google-ime-skk
  become: yes
  file: src={{ (google_ime_skk_path.stdout | dirname |dirname )+ '/bin/google-ime-skk' }} dest=/usr/local/bin/google-ime-skk state=link


- name: run scripts
  shell: "stat {{item.creates}} || ({{item.cmd}} && echo 'installed')"
  register: result
  changed_when: "'installed' in result.stdout"
  with_items: local_pkg__free_form
