---

- name: make directories
  file: path="{{item.dir}}" state=directory
  with_items: local_pkg__directories

- name: perform required git clones
  git:  dest="{{item.dest}}" repo="{{item.repo}}" remote="{{item.remote | default('origin') }}"
  with_items: local_pkg__git_clone

- name: run scripts
  shell: "stat {{item.creates}} || ({{item.cmd}} && echo 'installed')"
  register: result
  changed_when: "'installed' in result.stdout"
  with_items: local_pkg__free_form
