---
- name: include common role
  include_role: name=post_install/common

- name: create a systemd unit for emacs
  template: src=emacs.service.j2 dest="{{home}}/.config/systemd/user/emacs.service"

- name: enable emacs server on startup
  systemd: name=emacs user=yes enabled=yes state=started
