---
- name: make a directory for virtualenv
  file: path="{{home}}/venv" state=directory

- name: install packages into a virtualenv
  pip: name={{item}} state=present virtualenv="{{home}}/venv" extra_args='--user' virtualenv_command={{virtualenv_executable | default('virtualenv')}} virtualenv_site_packages=yes
  with_items: "{{python_pkg__packages}}"
