---

- name: install packages on Archlinux
  pacman: name={{item}} state=present
  become: yes
  when: ansible_os_family == 'Archlinux'
  with_flattened:
    - '{{sys_pkg__common}}'
    - '{{sys_pkg__arch}}'

- name: tap required repositories
  homebrew_tap: tap={{item}} state=present
  when: ansible_os_family == 'Darwin'
  with_items: '{{sys_pkg__brew_tap}}'

- name: install packages on Mac OS X
  homebrew: name={{item}} install_options={{sys_pkg__brew_options[item] | default('')}} state="{{ sys_pkg__brew_state[item] | default('present')}}"
  when: ansible_os_family == 'Darwin'
  with_flattened:
    - '{{sys_pkg__common}}'
    - '{{sys_pkg__mach}}'

- name: install packages on Mac OS X with homebrew-cask
  homebrew_cask: name={{item}} state=present
  when: ansible_os_family == 'Darwin'
  with_items: '{{sys_pkg__mach_with_cask}}'

- name: install packages on arch linux with yaourt
  shell: "yaourt -Qi {{item}} || yaourt --noconfirm -S {{item}}"
  with_items: '{{sys_pkg__arch_with_yaourt}}'
  when: ansible_os_family == 'Archlinux'
