---

- name: install packages on Archlinux
  pacman: name={{item}} state=present
  sudo: yes
  when: ansible_os_family == 'Archlinux'
  ignore_errors: yes
  with_flattened:
    - sys_pkg__common
    - sys_pkg__arch

- name: install packages on Mac OS X
  homebrew: name={{item}} state=present
  when: ansible_os_family == 'Darwin'
  with_flattened:
    - sys_pkg__common
    - sys_pkg__mach
