---
- hosts: localhost
  become: no
  pre_tasks:
    - name: check if sudo password is correct
      command: 'true'
      become: yes
      changed_when: False
    - include_vars: vars.yml
  roles:
    - vault
    - sys_pkg
    - link_cfg
    - r_pkg
    - node_pkg
    - local_pkg
    - python_pkg
    - supervisord
    - chrome_ext
    - post_install/common
    - role: post_install/mach
      become: yes
      when: ansible_os_family == 'Darwin'
