---

- hosts: localhost
  sudo: no
  vars:
    home: "{{lookup('env', 'HOME')}}"
  roles:
    - link_cfg
    - sys_pkg
    - r_pkg
    - local_pkg
    - role: post_install/mach
      sudo: yes
      when: ansible_os_family == 'Darwin'
