---
- hosts: localhost
  become: no
  pre_tasks:
    - name: check if sudo password is correct
      command: 'true'
      become: yes
      changed_when: False
    - include_vars: vars.yml
      tags: always
  roles:
    - { role: vault,       tags : [ 'vault' ] }
    - { role: sys_pkg,     tags : ['sys_pkg'] }
    - { role: link_cfg,    tags : ['link_cfg'] }
    - { role: r_pkg,       tags : ['r_pkg'] }
    - { role: node_pkg,    tags : ['node_pkg'] }
    - { role: local_pkg,   tags : ['local_pkg'] }
    - { role: python_pkg,  tags : ['python_pkg'] }
    - { role: supervisord, tags : ['supervisord'] }
    - role: chrome_ext
      become: "{{ansible_os_family != 'Darwin'}}"
      tags: [ 'chrome_ext' ]
    - role: post_install/Darwin
      become: yes
      tags: [ 'post_install' ]
      when: ansible_os_family == 'Darwin'
    - role: post_install/Archlinux
      tags: [ 'post_install' ]
      when: ansible_os_family != 'Darwin'
