---
- hosts: localhost
  sudo: no
  pre_tasks:
    - include_vars: vars.yml
  roles:
    - link_cfg
    - sys_pkg
    - r_pkg
    - local_pkg
    - role: post_install/mach
      sudo: yes
      when: ansible_os_family == 'Darwin'
