#!/bin/bash
set -eu

## We read value of multiuser.config in global git config and find out a config file
## that we would like to merge with global config.
## We suport reading only one file since it should suffice for our use case

## currently we skip setup of config if .prev_config file exists in .git directory

if [ "${GIT_DIR}" = "$(pwd)" ] ; then
## bare repository
## see https://git-scm.com/docs/githooks/2.9.2
    GIT_CFG_PATH="$(pwd)/config"
else
    GIT_CFG_PATH="$(pwd)/.git/config"
fi

function check_if_merged(){
  ## 1st argument: path to the gitconfig (something like ${worktree_root}/.git/config)

  set +e
  stat "$(dirname "${1}")/.prev_config" &> /dev/null
  if [ "$?" -eq 0 ] ; then
      echo "We skip setting up config since we have .prev_config file" >&2
      exit 0
  fi
  set -e
}

function get_additional_cfg(){
    ## the following command fails if multiuser.confdir is not set
    local my_conf_dir="$(git config multiuser.confdir)"
    ## we need to expand ~; otherwise ls fails
    local my_conf_dir="${my_conf_dir/#\~/${HOME}}"

    echo "Please input the prefix of the config file: " >&2
    exec < /dev/tty
    read conf_prefix

    local pattern="${my_conf_dir}/${conf_prefix}*"
    local candidates=($(ls -d ${pattern}))

    local num_matched_files="${#candidates[@]}"
    if [ "${num_matched_files}" -ne 1 ] ; then
        if [ "${num_matched_files}" -gt 1 ] ; then
            echo "More than 1 file matched with pattern: ${pattern}" >&2
            echo -e "The matched files are:\n${candidates[@]}\n" >&2
        else
            echo "no files mathched with pattern: ${pattern}" >&2
        fi
        echo -e "The files in ${my_conf_dir} are:\n$(echo ${my_conf_dir}/*)\n" >&2
        echo "aborted the commit." >&2
        exit 2
    fi

    echo "${candidates[0]}"
    return 0
}


function update_conf(){
    ## 1st argument: default config (something like ${worktree_dir}/.git/config)
    ## 2nd argument: additional config which override the default one
    cp "${1}" "$(dirname "${1}")/.prev_config"
    DEFAULT_CFG="${1}" ADDITIONAL_CFG="${2}" python2 <<EOF
from __future__ import print_function
from StringIO import StringIO
from ConfigParser import ConfigParser
import os

cfg_file = os.environ['DEFAULT_CFG']
override_file = os.environ['ADDITIONAL_CFG']
parser = ConfigParser()

for filename in [cfg_file, override_file]:
  with open(filename, "r") as cfg_io:
    ini = ''.join(map(lambda line: line.lstrip(), cfg_io.readlines()))
    parser.readfp(StringIO(ini))

with open(cfg_file, "w") as f:
  for section_name in parser.sections():
    f.write("[{}]\n".format(section_name))
    for k, v in parser.items(section_name):
      f.write("\t{} = {}\n".format(k, v))
EOF
}

check_if_merged "${GIT_CFG_PATH}"
additional_cfg="$(get_additional_cfg)"
update_conf "${GIT_CFG_PATH}" "${additional_cfg}"
## we need to reload config by exiting the current process
echo "update finished. Please retry the commit. (This commit will exit with 1)" >&2
exit 1
